# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bcMcdjyn3JSuuMipEZu1yLiuYLB7Mb5
"""

from keras import models
import librosa
import numpy as np

streaming_model.load_weights('weights.hd5')
f = '/content/test_wav.wav'
y,sr = librosa.load(f,sr=16000)
mat = librosa.feature.mfcc(y=y,sr=sr,n_mfcc=64,n_fft=int(sr*0.025),hop_length=int(sr*0.01))
n = mat.shape[1]%s
num_seqs = int(math.floor(mat.shape[1]/s))
mat1 = np.transpose(mat)
if n !=0:
  mat1 = mat1[:-n,:]
mat2 = mat1.reshape(num_seqs, s,dimn)

for s in range(num_seqs):
    in_seq = mat2[s].reshape( (1, s, dimn) )
    seq_pred = model.predict(in_seq)
    seq_pred = seq_pred.reshape(450) 
    for n in range(s):
        in_feature_vector = mat2[s][n].reshape(1,1,dimn)
        single_pred = streaming_model.predict(in_feature_vector)[0]
        print('difference' seq_pred[n] - single_pred)
    streaming_model.reset_states()